# This is a sample production config (to be deployed in the WEB-INF directory).
# This is the same as what Google Registry runs in production, except with
# placeholders for Google-specific settings.

appEngine:
  projectId: placeholder
  # The "tools-dot-" prefix is used on the project ID in this URL in order to
  # get around an issue with double-wildcard SSL certs.
  toolsServiceUrl:
    hostName: tools-dot-placeholder.appspot.com
    port: 443

gSuite:
  domainName: placeholder
  outgoingEmailDisplayName: placeholder
  outgoingEmailAddress: placeholder
  adminAccountEmailAddress: placeholder

registryPolicy:
  contactAndHostRoidSuffix: placeholder
  productName: placeholder
  greetingServerId: placeholder
  registrarChangesNotificationEmailAddresses:
    - placeholder
    - placeholder
  defaultRegistrarWhoisServer: placeholder
  tmchCaMode: PRODUCTION
  tmchCrlUrl: http://crl.icann.org/tmch.crl
  tmchMarksDbUrl: https://ry.marksdb.org
  checkApiServletClientId: placeholder
  registryAdminClientId: placeholder
  whoisDisclaimer: |
    multi-line
    placeholder

icannReporting:
  icannTransactionsReportingUploadUrl: https://ry-api.icann.org/report/registrar-transactions
  icannActivityReportingUploadUrl: https://ry-api.icann.org/report/registry-functions-activity

oAuth:
  allowedOauthClientIds:
    - placeholder.apps.googleusercontent.com

rde:
  reportUrlPrefix: https://ry-api.icann.org/report/registry-escrow-report
  uploadUrl: sftp://placeholder@sftpipm2.ironmountain.com/Outbox
  sshIdentityEmailAddress: placeholder

registrarConsole:
  logoFilename: placeholder
  supportPhoneNumber: placeholder
  supportEmailAddress: placeholder
  announcementsEmailAddress: placeholder
  integrationEmailAddress: placeholder
  technicalDocsUrl: https://drive.google.com/drive/folders/placeholder

misc:
  sheetExportId: placeholder

kms:
  projectId: placeholder
