package(default_visibility = ["//visibility:public"])

java_library(
    name = "http",
    exports = [
        "@google_api_client//jar",
        "@google_api_client_appengine//jar",
        "@google_http_client_appengine//jar",
    ],
)
