package(
    default_visibility = ["//java/com/google/domain/registry:registry_project"],
)


java_library(
    name = "params",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/common/annotations",
        "//java/com/google/common/base",
        "//java/com/google/common/collect",
        "//java/com/google/common/net",
        "//java/com/google/common/primitives",
        "//java/com/google/domain/registry/model",
        "//java/com/google/domain/registry/util",
        "//third_party/java/jcommander",
        "//third_party/java/joda_money",
        "//third_party/java/joda_time",
        "//third_party/java/jsr305_annotations",
    ],
)
