package(default_visibility = ["//visibility:public"])

java_library(
    name = "oauth2",
    exports = [
        "@google_api_client//jar",
        "@google_api_client_appengine//jar",
        "@google_oauth_client_appengine//jar",
    ],
)
