package(default_visibility = ["//third_party/java_src/gtld:__subpackages__"])

licenses(["notice"])  # Apache 2.0


package_group(
    name = "registry_project",
    packages = [
        "//java/google/registry/...",
        "//javatests/google/registry/...",
    ],
)

