package(default_visibility = ["//java/google/registry:registry_project"])

licenses(["notice"])  # Apache 2.0


package_group(
    name = "registry_project",
    packages = [
        "//java/google/registry/...",
        "//javatests/google/registry/...",
    ],
)

