package(default_visibility = ["//visibility:public"])

java_library(
    name = "gdata",
    exports = ["@gdata_core//jar"],
)

java_library(
    name = "spreadsheet",
    exports = ["@gdata_core//jar"],
)
