package(
    default_visibility = ["//java/com/google/domain/registry:registry_project"],
)


java_library(
    name = "api",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/common/base",
        "//third_party/java/dagger",
        "//third_party/java/jsr305_annotations",
        "//third_party/java/jsr330_inject",
    ],
)
