package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

java_library(
    name = "metrics",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_auto_value",
        "@com_google_code_findbugs_jsr305",
        "@com_google_dagger",
        "@com_google_errorprone_error_prone_annotations",
        "@com_google_guava",
        "@com_google_re2j",
        "@joda_time",
    ],
)
