package(default_visibility = ["//visibility:public"])

java_library(
    name = "cloud_dns_v2beta1_versioned",
    exports = ["@google_api_services_dns//jar"],
    runtime_deps = [
        "@google_api_client//jar",
    ],
)
