package(default_visibility = ["//java/com/google/domain/registry:registry_project"])


filegroup(
    name = "externs",
    srcs = glob(["*.js"]),
)

filegroup(
    name = "js_files_recursive",
    srcs = glob(["*.js"]),
)
