package(default_visibility = ["//visibility:public"])

java_library(
    name = "oauth2",
    exports = [
        "@google_api_client//jar",
        "@google_http_client//jar",
        "@google_oauth_client//jar",
    ],
)
