package(default_visibility = ["//java/com/google/domain/registry:registry_project"])


java_library(
    name = "forms",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//java/com/google/common/annotations",
        "//java/com/google/common/base",
        "//java/com/google/common/collect",
        "//third_party/java/jsr305_annotations",
    ],
)
