package(default_visibility = ["//java/google/registry:registry_project"])

licenses(["notice"])  # Apache 2.0


filegroup(
    name = "externs",
    srcs = glob(["*.js"]),
)

filegroup(
    name = "js_files_recursive",
    srcs = glob(["*.js"]),
)
