package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

java_library(
    name = "forms",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_code_findbugs_jsr305",
        "@com_google_guava",
        "@com_google_re2j",
    ],
)
