package(default_visibility = ["//visibility:public"])

java_library(
    name = "jackson2",
    exports = [
        "@google_api_client//jar",
        "@google_http_client_jackson2//jar",
    ],
    runtime_deps = [
        "@jackson_core//jar",
    ],
)
