package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0


java_library(
    name = "writer",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/common/annotations",
        "//java/com/google/common/base",
        "//java/com/google/common/collect",
        "//third_party/java/dagger",
    ],
)
