package(default_visibility = ["//visibility:public"])

java_library(
    name = "monitoring_java_lib",
    exports = [
        "@google_api_services_monitoring//jar",
    ],
    runtime_deps = [
        "@google_api_client//jar",
    ],
)
